# Generated by Django 3.1.12 on 2021-10-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancelacion',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=500)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('marca', models.CharField(max_length=20)),
                ('año', models.IntegerField()),
                ('modelo', models.CharField(max_length=20)),
                ('problema', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=5)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=16)),
                ('passwordconfirm', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
