# Generated by Django 3.1.12 on 2021-11-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_auto_20211023_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.EmailField(max_length=254)),
                ('email', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('mensaje', models.CharField(max_length=500)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
