# Generated by Django 3.1.12 on 2021-11-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0004_auto_20211120_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('code', models.CharField(max_length=20)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
