# Generated by Django 3.0.8 on 2021-11-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0005_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
