# Generated by Django 3.0.8 on 2021-11-23 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0006_code_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='email',
        ),
    ]
